name: Docker Image CI

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:        
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2.3.0
        with:
          registry: ghcr.io
          #username: "fdarveau"
          #password: ${{ secrets.PAT }}
          #repository: fdarveau/cors-anywhere
          tags: fdarveau/cors-anywhere:$(date +%s),fdarveau/cors-anywhere:latest
